CREATE TABLE IF NOT EXISTS users(
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts(
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  iban VARCHAR(34) UNIQUE NOT NULL,
  balance NUMERIC(18,2) NOT NULL DEFAULT 0
);
